version: '3.7'
services:
    backend-server:
        image: backend-server
        restart: unless-stopped
        ports:
            - "6000:6000"
        networks:
            - mern-app
        depends_on:
            - mongo

    mongo:
        image: mongo:4.4-bionic
        ports:
            - "27017:27017"
        networks:
            - mern-app
        volumes:
            - mongo-data:/data/db

networks:
    mern-app:
        driver: bridge

volumes:
    mongo-data:
        driver: local